# pyproject.toml 
[build-system]
requires = ["setuptools>=61.0", "wheel", "pybind11[global]>=2.10"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrex-rocksdb"
version = "0.1.1a"
authors = [
  { name="Charilaos Mylonas", email="mylonas.charilaos@gmail.com" },
]
description = "A fast RocksDB wrapper for Python using pybind11."
readme = "README.md"
requires-python = ">=3.8"
keywords = ["rocksdb", "database", "key-value", "pybind11"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Database",
]

[project.urls]
Homepage = "https://github.com/mylonasc/pyrex"
Repository = "https://github.com/mylonasc/pyrex"

[project.optional-dependencies]
dev = [
    "pytest",
    "sphinx",
    "sphinx-rtd-theme",
    "cibuildwheel",
    "twine"
]

# Crucial for src layout
[tool.setuptools]
packages = ["pyrex"] # Explicitly list your package
package-dir = {"" = "src"} # Tell setuptools to look in 'src' for packages

[tool.cibuildwheel]
# Global build filter and skip patterns.
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
skip = ["*-musllinux_*"]

# Linux specific configurations
[tool.cibuildwheel.linux]
before-build = """
  yum install -y rocksdb-devel snappy-devel lz4-devel zlib-devel bzip2-devel || \\
  (apt-get update && apt-get install -y librocksdb-dev libsnappy-dev liblz4-dev zlib1g-dev libbz2-dev)
  echo "--- Debugging inside manylinux container after RocksDB install (via rpm -ql) ---"
  echo "Files installed by rocksdb-devel:"
  rpm -ql rocksdb-devel || true
  echo "Files installed by rocksdb (main library):"
  rpm -ql rocksdb || true
  echo "--- End rpm -ql output ---"
"""
environment = "CFLAGS='-I/usr/include/' LDFLAGS='-L/usr/lib/ -lrocksdb'"


# macOS specific configurations
[tool.cibuildwheel.macos]
# Note: BREW_PREFIX is an environment variable set by the GitHub Actions workflow.
# We will use setup-args to directly pass include and library directories to setuptools.
# environment = "CFLAGS='-I${BREW_PREFIX}/include/' LDFLAGS='-L${BREW_PREFIX}/lib/ -lrocksdb'"
environment = "MACOSX_DEPLOYMENT_TARGET=14.0"
before-build = """
  echo "Setting CFLAGS and LDFLAGS explicitly in before-build hook..."
  echo "-- brew prefix: ${BREW_PREFIX}"
  export CFLAGS="-I${BREW_PREFIX}/include/"
  export LDFLAGS="-L${BREW_PREFIX}/lib/ -lrocksdb"
  echo "CFLAGS set: $CFLAGS"
  echo "LDFLAGS set: $LDFLAGS"
  # You might also try:
  # export CXXFLAGS="$CFLAGS" # Sometimes CXXFLAGS is used for C++
"""


# Windows specific configurations
[tool.cibuildwheel.windows]
build = "cp39-win_amd64"
archs = ["AMD64"]
environment = { INCLUDE = "D:\\a\\pyrex\\pyrex\\vcpkg\\installed\\x64-windows\\include;${INCLUDE}", LIB = "D:\\a\\pyrex\\pyrex\\vcpkg\\installed\\x64-windows\\lib;${LIB}" }

