# .github/workflows/build_wheels.yml

name: Build Python Wheels

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
      - fix-windows-build
      - develop # Optional: Trigger on pushes to a 'develop' branch
  pull_request:
    branches:
      - main
      - fix-windows-build
      - develop
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120 # Set a higher timeout for the job (e.g., 45 minutes)
    strategy:
      # Define a matrix to build on different OS
      matrix:
        os: [windows-latest] #, macos-latest, windows-latest]
        # cibuildwheel will manage the specific Python versions (e.g., cp38, cp39, etc.)
        # within each OS environment, so we don't need to list them explicitly here.

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch all history for setuptools_scm if you use it for dynamic versioning
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # cibuildwheel handles specific Python versions

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel # Install cibuildwheel

    - name: Install RocksDB (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install rocksdb

    - name: Get Homebrew prefix (macOS)
      if: runner.os == 'macOS'
      id: brew_prefix
      run: echo "BREW_PREFIX=$(brew --prefix)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Debug RocksDB Paths (macOS)
      if: runner.os == 'macOS'
      run: |
        BREW_PREFIX="${{ steps.brew_prefix.outputs.BREW_PREFIX }}"
        echo "Homebrew prefix: $BREW_PREFIX"
        echo "--- Listing contents of $BREW_PREFIX/include/ ---"
        ls -R "$BREW_PREFIX/include/" | grep -E "rocksdb|db.h" || true
        echo "--- Listing contents of $BREW_PREFIX/lib/ ---"
        ls -R "$BREW_PREFIX/lib/" | grep -E "rocksdb|librocksdb" || true
        echo "--- Searching for db.h globally (within brew prefix) ---"
        find "$BREW_PREFIX" -name "db.h" 2>/dev/null | grep "rocksdb" || true
        echo "--- Checking dynamic libraries for rocksdb (within brew prefix) ---"
        find "$BREW_PREFIX/lib" -name "librocksdb*.dylib" || true
      shell: bash

    - name: Debug RocksDB Paths (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "--- Listing contents of VCPKG_ROOT include directory ---"
        dir "${{ env.VCPKG_ROOT }}\installed\x64-windows\include\rocksdb" /s || true
        echo "--- Listing contents of VCPKG_ROOT lib directory ---"
        dir "${{ env.VCPKG_ROOT }}\installed\x64-windows\lib" /s || true
        echo "--- Searching for rocksdb.h ---"
        Get-ChildItem -Path "${{ env.VCPKG_ROOT }}\installed\x64-windows\include" -Filter "db.h" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName || true
        echo "--- Searching for rocksdb.lib/dll ---"
        Get-ChildItem -Path "${{ env.VCPKG_ROOT }}\installed\x64-windows\lib" -Filter "rocksdb*" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName || true
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      shell: pwsh

    - name: Export GitHub Actions cache environment variables (for Windows)
      uses: actions/github-script@v7 # Use a recent version
      if: runner.os == 'Windows' # Only needed for Windows, or where vcpkg is used
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install RocksDB (Windows via vcpkg)
      if: runner.os == 'Windows'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
        .\vcpkg\vcpkg.exe install rocksdb:x64-windows
        echo ${{ env.VCPKG_ROOT }}
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"


    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD_LINUX: "cp*-manylinux_x86_64" # This will target all CPython versions for manylinux_x86_64
        CIBW_SKIP: "*-musllinux_*" # Skips all Python versions and architectures for musllinux


        # Install RocksDB inside the manylinux container before the build
        CIBW_BEFORE_BUILD_LINUX: |
          # Try yum install first (for CentOS/RHEL-based manylinux images)
          yum install -y rocksdb-devel snappy-devel lz4-devel zlib-devel bzip2-devel || \
          # Fallback to apt-get (for Debian/Ubuntu-based manylinux images, though less common)
          (apt-get update && apt-get install -y librocksdb-dev libsnappy-dev liblz4-dev zlib1g-dev libbz2-dev)

          echo "--- Debugging inside manylinux container after RocksDB install (via rpm -ql) ---"
          echo "Files installed by rocksdb-devel:"
          rpm -ql rocksdb-devel || true
          echo "Files installed by rocksdb (main library):"
          rpm -ql rocksdb || true
          echo "--- End rpm -ql output ---"

        # Explicitly set CFLAGS and LDFLAGS for cibuildwheel to pass directly to the compiler.
        # These will need to be adjusted based on the rpm -ql output from the next run.
        CIBW_CFLAGS_LINUX: "-I/usr/include/"
        CIBW_LDFLAGS_LINUX: "-L/usr/lib/ -lrocksdb"

        # macOS specific flags (using the dynamically determined Homebrew prefix)
        CIBW_CFLAGS_MACOS: "-I${{ steps.brew_prefix.outputs.BREW_PREFIX }}/include/"
        CIBW_LDFLAGS_MACOS: "-L${{ steps.brew_prefix.outputs.BREW_PREFIX }}/lib/ -lrocksdb"

        # Windows specific flags (adjust based on vcpkg output)
        CIBW_CFLAGS_WINDOWS: "-I${{ github.workspace }}\\vcpkg\\installed\\x64-windows\\include"
        CIBW_LDFLAGS_WINDOWS: "-L${{ github.workspace }}\\vcpkg\\installed\\x64-windows\\lib -lrocksdb"

        # Other cibuildwheel environment variables (if needed for other purposes)
        # CIBW_SKIP: "pp* cp36* cp37*"
        # CIBW_ARCHS_WINDOWS: "AMD64"

    - name: Upload wheels as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-wheels
        path: ./wheelhouse/*.whl

    # Optional: Add a step to publish to PyPI on release tags
    # - name: Publish to PyPI
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    #   run: |
    #     pip install twine
    #     twine upload --non-interactive --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} wheelhouse/*.whl
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

