# .github/workflows/build_wheels.yml
name: Build Python Wheels

on:
  push:
    branches:
      - main
      - fix-windows-build
      - develop
  pull_request:
    branches:
      - main
      - fix-windows-build
      - develop
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120 # Set a higher timeout for the job (e.g., 120 minutes)
    permissions:
      contents: read
      packages: write # Crucial for pushing to GitHub Packages
    strategy:
      matrix:
        os: [windows-latest] #[ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false # Ensures all jobs run even if one fails
    env:
      # Define VCPKG_ROOT for Windows (used in Windows-specific steps)
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg

      # --- Global CIBW environment variables (reintroduced) ---
      # These flags are intended to be set as environment variables, not in pyproject.toml.
      CIBW_FORCE_INSTALL: "1"
      CIBW_DEBUG: "1"
      CIBW_PRERELEASE_PYTHONS: "True"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # cibuildwheel will manage specific Python versions
        architecture: 'x64' # Ensure 64-bit Python is set up

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel

#    # --- NEW DIAGNOSTIC STEP FOR WINDOWS ---
#    - name: Diagnose NuGet Python Packages (Windows Only)
#      if: runner.os == 'Windows'
#      shell: pwsh # Using PowerShell for consistency with other Windows steps
#      run: |
#        Write-Host "--- Checking NuGet connectivity for Python packages ---"
#        # Ensure nuget.exe is available; it usually is on GitHub Actions Windows runners.
#        # Use -Source to explicitly target the main NuGet feed.
#        # -AllVersions and -PreRelease to see everything.
#        # -Verbosity detailed for maximum diagnostic info.
#        nuget list python -Source https://api.nuget.org/v3/index.json -AllVersions -PreRelease -Verbosity detailed
#        Write-Host "--- NuGet check complete ---"
#    # ---------------------------------------

    # --- macOS Specific Steps ---
    - name: Install RocksDB (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install rocksdb

    - name: Get Homebrew prefix (macOS)
      if: runner.os == 'macOS'
      # Set BREW_PREFIX as an environment variable that cibuildwheel will pick up
      run: echo "BREW_PREFIX=$(brew --prefix)" >> $GITHUB_ENV
      shell: bash

    - name: Debug RocksDB Paths (macOS)
      if: runner.os == 'macOS'
      run: |
        echo "Homebrew prefix: ${{ env.BREW_PREFIX }}"
        echo "--- Listing contents of ${{ env.BREW_PREFIX }}/include/ ---"
        ls -R "${{ env.BREW_PREFIX }}/include/" | grep -E "rocksdb|db.h" || true
        echo "--- Listing contents of ${{ env.BREW_PREFIX }}/lib/ ---"
        ls -R "${{ env.BREW_PREFIX }}/lib/" | grep -E "rocksdb|librocksdb" || true
      shell: bash

    # --- Windows Specific Steps (Vcpkg and RocksDB Installation) ---
    - name: Export GitHub Actions cache environment variables (for Windows)
      uses: actions/github-script@v7
      if: runner.os == 'Windows'
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');


    - name: Install RocksDB (Windows via vcpkg)
      if: runner.os == 'Windows'
      run: |
        # 1. Bootstrap vcpkg
        git clone https://github.com/microsoft/vcpkg.git "${{ env.VCPKG_ROOT }}"
        cmd /c "`"${{ env.VCPKG_ROOT }}\bootstrap-vcpkg.bat`" -disableMetrics"
        
        # 2. Get the path to the nuget.exe that vcpkg uses internally.
        # This command outputs the path directly to stdout.
        $NuGetExePath = & "${{ env.VCPKG_ROOT }}\vcpkg.exe" fetch nuget
        
        # Trim any whitespace, newlines, or quotation marks from the output.
        $NuGetExePath = $NuGetExePath.Trim()
        $NuGetExePath = $NuGetExePath.Trim('"')
        # Verify that the nuget.exe path was successfully retrieved.
        if (-not (Test-Path $NuGetExePath)) {
            Write-Error "Error: Vcpkg's nuget.exe not found at $NuGetExePath. Fetch command might have failed."
            exit 1
        }
        Write-Host "Vcpkg's nuget.exe path: $NuGetExePath"
        # 3. Define variables for NuGet feed configuration.
        $Owner = "${{ github.repository_owner }}"
        $FeedUrl = "https://nuget.pkg.github.com/$Owner/index.json"
        $Username = "$Owner"
        $Password = "${{ github.token }}"
        
        # 4. Add the 'github' source using vcpkg's nuget.exe.
        # This command modifies the default NuGet.Config for this user/environment,
        # which vcpkg's internal nuget.exe is likely to use.
        & "$NuGetExePath" sources add `
            -Name github `
            -Source "$FeedUrl" `
            -UserName "$Username" `
            -Password "$Password" `
            -ProtocolVersion 3 `
            -StorePasswordInClearText # Required for the GitHub token to work as a password.

    
        # 5. Determine the standard NuGet.Config location and add package source mapping.
        $NuGetConfigDir = Join-Path -Path $env:APPDATA -ChildPath "NuGet"
        $NuGetConfigFile = Join-Path -Path $NuGetConfigDir -ChildPath "NuGet.Config"
        New-Item -ItemType Directory -Path $NuGetConfigDir -Force | Out-Null
        Write-Host "Modifying NuGet.Config at: $NuGetConfigFile"

        [xml]$config = Get-Content -Path $NuGetConfigFile -Encoding UTF8
        $packageSourceMapping = $config.configuration.packageSourceMapping
        if (-not $packageSourceMapping) {
          $packageSourceMapping = $config.configuration.AppendChild($config.CreateElement("packageSourceMapping"))
        }

        # Clear any existing mappings to ensure a clean state
        $packageSourceMapping.RemoveAll()

        # --- START OF CHANGES ---

        # A. Add the default nuget.org source if it doesn't exist
        $nugetSource = $config.configuration.packageSources.SelectSingleNode("add[@key='nuget.org']")
        if (-not $nugetSource) {
            $nugetSource = $config.CreateElement("add")
            $nugetSource.SetAttribute("key", "nuget.org")
            $nugetSource.SetAttribute("value", "https://api.nuget.org/v3/index.json")
            $config.configuration.packageSources.AppendChild($nugetSource)
        }

        # B. Define a mapping for the public nuget.org feed to be the default
        $publicSourceMapping = $packageSourceMapping.AppendChild($config.CreateElement("packageSource"))
        $publicSourceMapping.SetAttribute("key", "nuget.org")
        $catchAllPattern = $publicSourceMapping.AppendChild($config.CreateElement("package"))
        $catchAllPattern.SetAttribute("pattern", "*") # This is the crucial part

        # --- END OF CHANGES ---

        # C. Define the mapping for your private GitHub feed
        $githubSourceMapping = $packageSourceMapping.AppendChild($config.CreateElement("packageSource"))
        $githubSourceMapping.SetAttribute("key", "github")
        $patterns = @(
          "rocksdb_x64-windows",
          "zlib_x64-windows",
          "lz4_x64-windows",
          "snappy_x64-windows",
          "vcpkg-cmake_x64-windows",
          "vcpkg-cmake-config_x64-windows"
        )
        foreach ($pattern in $patterns) {
          $packageNode = $githubSourceMapping.AppendChild($config.CreateElement("package"))
          $packageNode.SetAttribute("pattern", $pattern)
        }
        $config.Save($NuGetConfigFile)
    
        Write-Host "--- Raw content of NuGet.Config (after vcpkg's nuget.exe config) ---"
        Get-Content -Path $NuGetConfigFile -Raw
        Write-Host "----------------------------------"
    
        # 6. Install RocksDB using vcpkg
        & "${{ env.VCPKG_ROOT }}\vcpkg.exe" install rocksdb:x64-windows --debug
      shell: pwsh
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg
        VCPKG_BINARY_SOURCES: "clear;nuget,github,readwrite"
        VCPKG_DEBUG: 1


#    - name: Set build environment variables (Windows)
#      if: runner.os == 'Windows'
#      shell: pwsh
#      run: |
#        $VCPKG_ROOT_WIN = "${{ env.VCPKG_ROOT }}"
#        $ROCKSDB_INCLUDE_PATH = Join-Path -Path $VCPKG_ROOT_WIN -ChildPath "installed\x64-windows\include"
#        $ROCKSDB_LIB_PATH = Join-Path -Path $VCPKG_ROOT_WIN -ChildPath "installed\x64-windows\lib"
#        # Zlib headers are usually in the same include path as RocksDB in vcpkg
#        $ZLIB_INCLUDE_PATH = Join-Path -Path $VCPKG_ROOT_WIN -ChildPath "installed\x64-windows\include"
#        # Zlib lib is usually in the same lib path as RocksDB in vcpkg
#        $ZLIB_LIB_PATH = Join-Path -Path $VCPKG_ROOT_WIN -ChildPath "installed\x64-windows\lib"

#        Write-Host "Setting INCLUDE environment variable to include: $ROCKSDB_INCLUDE_PATH"
#        Write-Host "Setting LIB environment variable to include: $ROCKSDB_LIB_PATH"

#        # Set for the CURRENT PowerShell session and for subsequent steps
#        # Append existing values to ensure other system paths are preserved
#        $env:INCLUDE = "$ROCKSDB_INCLUDE_PATH;$env:INCLUDE"
#        $env:LIB = "$ROCKSDB_LIB_PATH;$env:LIB"

#        # Update GITHUB_ENV for subsequent steps
#        echo "INCLUDE=$env:INCLUDE" | Out-File -FilePath $env:GITHUB_ENV -Append
#        echo "LIB=$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Append

#        # Set CFLAGS and LDFLAGS for the CURRENT session
#        # Ensure correct quoting for paths with spaces if they ever arise
#        $env:CFLAGS = "-I`"$ROCKSDB_INCLUDE_PATH`" -I`"$ZLIB_INCLUDE_PATH`""
#        # LDFLAGS now includes RocksDB, Shlwapi, Rpcrt4, and Zlib
#        $env:LDFLAGS = "-L`"$ROCKSDB_LIB_PATH`" -L`"$ZLIB_LIB_PATH`" -lrocksdb -lshlwapi -lrpcrt4 -lzlib"

#        # Update GITHUB_ENV for subsequent steps with the full CFLAGS/LDFLAGS
#        echo "CFLAGS=$env:CFLAGS" | Out-File -FilePath $env:GITHUB_ENV -Append
#        echo "LDFLAGS=$env:LDFLAGS" | Out-File -FilePath $env:GITHUB_ENV -Append # <-- This was the corrected line


#        Write-Host "Current (after setting in current session) INCLUDE: $env:INCLUDE"
#        Write-Host "Current (after setting in current session) LIB: $env:LIB"
#        Write-Host "Current (after setting in current session) CFLAGS: $env:CFLAGS"
#        Write-Host "Current (after setting in current session) LDFLAGS: $env:LDFLAGS"        

#    - name: Debug RocksDB Paths (Windows)
#      if: runner.os == 'Windows'
#      continue-on-error: true
#      run: |
#        echo "Current VCPKG_ROOT value: ${{ env.VCPKG_ROOT }}"
#        echo "--- Listing contents of VCPKG_ROOT include directory ---"
#        $RocksDBIncludePath = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\include\rocksdb"
#        Get-ChildItem -Path $RocksDBIncludePath -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
#        echo "--- Listing contents of VCPKG_ROOT lib directory ---"
#        $RocksDBLibPath = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\lib"
#        Get-ChildItem -Path $RocksDBLibPath -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
#        echo "--- Searching for rocksdb.h ---"
#        $RocksDBHeadersRoot = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\include"
#        Get-ChildItem -Path $RocksDBHeadersRoot -Filter "db.h" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
#        echo "--- Searching for rocksdb.lib/dll ---"
#        $RocksDBLibsRoot = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\lib"
#        Get-ChildItem -Path $RocksDBLibsRoot -Filter "rocksdb*" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
#      env:
#        VCPKG_ROOT: ${{ github.workspace }}\vcpkg
#      shell: pwsh

    # --- Build Wheels Step ---
    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse

    - name: Upload wheels as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-wheels
        path: ./wheelhouse/*.whl
