# .github/workflows/build_wheels.yml
name: Build Python Wheels

on:
  push:
    branches:
      - main
      - fix-windows-build
      - develop
  pull_request:
    branches:
      - main
      - fix-windows-build
      - develop
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120 # Set a higher timeout for the job (e.g., 120 minutes)
    permissions:
      contents: read
      packages: write # <-- THIS IS CRUCIAL FOR PUSHING TO GITHUB PACKAGES
    strategy:
      matrix:
        os: [windows-latest] #, macos-latest, windows-latest]
    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg # Define VCPKG_ROOT for Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # Use a general 3.x version. cibuildwheel will manage specific Python versions
        # within its isolated environments.
        python-version: '3.x'
        architecture: 'x64' # Ensure 64-bit Python is set up

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel # Install cibuildwheel

    # --- macOS Specific Steps (Keep as is) ---
    - name: Install RocksDB (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install rocksdb

    - name: Get Homebrew prefix (macOS)
      if: runner.os == 'macOS'
      id: brew_prefix
      run: echo "BREW_PREFIX=$(brew --prefix)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Debug RocksDB Paths (macOS)
      if: runner.os == 'macOS'
      run: |
        BREW_PREFIX="${{ steps.brew_prefix.outputs.BREW_PREFIX }}"
        echo "Homebrew prefix: $BREW_PREFIX"
        echo "--- Listing contents of $BREW_PREFIX/include/ ---"
        ls -R "$BREW_PREFIX/include/" | grep -E "rocksdb|db.h" || true
        echo "--- Listing contents of $BREW_PREFIX/lib/ ---"
        ls -R "$BREW_PREFIX/lib/" | grep -E "rocksdb|librocksdb" || true
        echo "--- Searching for db.h globally (within brew prefix) ---"
        find "$BREW_PREFIX" -name "db.h" 2>/dev/null | grep "rocksdb" || true
        echo "--- Checking dynamic libraries for rocksdb (within brew prefix) ---"
        find "$BREW_PREFIX/lib" -name "librocksdb*.dylib" || true
      shell: bash

    # --- Windows Specific Steps (Vcpkg and RocksDB Installation) ---
    - name: Export GitHub Actions cache environment variables (for Windows)
      uses: actions/github-script@v7 # Use a recent version
      if: runner.os == 'Windows' # Only needed for Windows, or where vcpkg is used
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install RocksDB (Windows via vcpkg)
      if: runner.os == 'Windows'
      run: |
        # 1. Bootstrap vcpkg
        git clone https://github.com/microsoft/vcpkg.git "${{ env.VCPKG_ROOT }}"
        cmd /c "`"${{ env.VCPKG_ROOT }}\bootstrap-vcpkg.bat`" -disableMetrics"

        # 2. Get the path to the nuget.exe that vcpkg uses internally.
        $NuGetExePath = & "${{ env.VCPKG_ROOT }}\vcpkg.exe" fetch nuget
        $NuGetExePath = $NuGetExePath.Trim().Trim('"') # Trim whitespace and quotes
        if (-not (Test-Path $NuGetExePath)) {
            Write-Error "Error: Vcpkg's nuget.exe not found at $NuGetExePath. Fetch command might have failed."
            exit 1
        }
        Write-Host "Vcpkg's nuget.exe path: $NuGetExePath"

        # 3. Define variables for NuGet feed configuration.
        $Owner = "${{ github.repository_owner }}"
        $FeedUrl = "https://nuget.pkg.github.com/$Owner/index.json"
        $Username = "$Owner"
        $Password = "${{ github.token }}"

        # 4. Add the 'github' source using vcpkg's nuget.exe.
        & "$NuGetExePath" sources add `
            -Name github `
            -Source "$FeedUrl" `
            -UserName "$Username" `
            -Password "$Password" `
            -ProtocolVersion 3 `
            -StorePasswordInClearText

        # 5. Determine the standard NuGet.Config location and add package source mapping.
        $NuGetConfigDir = Join-Path -Path $env:APPDATA -ChildPath "NuGet"
        $NuGetConfigFile = Join-Path -Path $NuGetConfigDir -ChildPath "NuGet.Config"
        New-Item -ItemType Directory -Path $NuGetConfigDir -Force | Out-Null
        Write-Host "Modifying NuGet.Config at: $NuGetConfigFile"

        [xml]$config = Get-Content -Path $NuGetConfigFile -Encoding UTF8
        $packageSourceMapping = $config.configuration.packageSourceMapping
        if (-not $packageSourceMapping) {
            $packageSourceMapping = $config.configuration.AppendChild($config.CreateElement("packageSourceMapping"))
        }
        $githubSourceMapping = $packageSourceMapping.SelectSingleNode("packageSource[@key='github']")
        if (-not $githubSourceMapping) {
            $githubSourceMapping = $packageSourceMapping.AppendChild($config.CreateElement("packageSource"))
            $githubSourceMapping.SetAttribute("key", "github")
        }
        $githubSourceMapping.RemoveAll() # Clear existing patterns
        $githubSourceMapping.SetAttribute("key", "github") # Re-add key

        # Define the package patterns. Adjust these if vcpkg uses different package IDs.
        $patterns = @(
            "rocksdb_x64-windows",
            "zlib_x64-windows",
            "lz4_x64-windows",
            "snappy_x64-windows",
            "vcpkg-cmake_x64-windows",
            "vcpkg-cmake-config_x64-windows"
        )
        foreach ($pattern in $patterns) {
            $packageNode = $githubSourceMapping.AppendChild($config.CreateElement("package"))
            $packageNode.SetAttribute("pattern", $pattern)
        }
        $config.Save($NuGetConfigFile)

        Write-Host "--- Raw content of NuGet.Config (after vcpkg's nuget.exe config) ---"
        Get-Content -Path $NuGetConfigFile -Raw
        Write-Host "----------------------------------"
        Write-Host "--- Verifying sources with vcpkg's nuget.exe ---"
        & "$NuGetExePath" sources list -ConfigFile "$NuGetConfigFile" -Verbosity detailed -ForceEnglishOutput
        Write-Host "------------------------------------------------"

        # 6. Install RocksDB using vcpkg, which will now use the configured NuGet cache.
        & "${{ env.VCPKG_ROOT }}\vcpkg.exe" install rocksdb:x64-windows --debug
        echo "VCPKG_ROOT: ${{ env.VCPKG_ROOT }}" # Confirm VCPKG_ROOT is set correctly
      shell: pwsh
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg
        VCPKG_BINARY_SOURCES: "clear;nuget,github,readwrite" # Crucial for vcpkg to use your cache
        VCPKG_DEBUG: 1 # Add this line for verbose output from vcpkg

    - name: Debug RocksDB Paths (Windows)
      if: runner.os == 'Windows'
      continue-on-error: true
      run: |
        echo "Current VCPKG_ROOT value: ${{ env.VCPKG_ROOT }}"
        echo "--- Listing contents of VCPKG_ROOT include directory ---"
        $RocksDBIncludePath = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\include\rocksdb"
        Get-ChildItem -Path $RocksDBIncludePath -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
        echo "--- Listing contents of VCPKG_ROOT lib directory ---"
        $RocksDBLibPath = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\lib"
        Get-ChildItem -Path $RocksDBLibPath -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
        echo "--- Searching for rocksdb.h ---"
        $RocksDBHeadersRoot = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\include"
        Get-ChildItem -Path $RocksDBHeadersRoot -Filter "db.h" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
        echo "--- Searching for rocksdb.lib/dll ---"
        $RocksDBLibsRoot = Join-Path -Path "${{ env.VCPKG_ROOT }}" -ChildPath "installed\x64-windows\lib"
        Get-ChildItem -Path $RocksDBLibsRoot -Filter "rocksdb*" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      shell: pwsh

    # --- Build Wheels Step (with crucial cibuildwheel and RocksDB fixes) ---
    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse
      env:
        # Linux specific configurations
        CIBW_BUILD_LINUX: "cp*-manylinux_x86_64"
        CIBW_SKIP: "*-musllinux_*"
        CIBW_BEFORE_BUILD_LINUX: |
          yum install -y rocksdb-devel snappy-devel lz4-devel zlib-devel bzip2-devel || \
          (apt-get update && apt-get install -y librocksdb-dev libsnappy-dev liblz4-dev zlib1g-dev libbz2-dev)
          echo "--- Debugging inside manylinux container after RocksDB install (via rpm -ql) ---"
          echo "Files installed by rocksdb-devel:"
          rpm -ql rocksdb-devel || true
          echo "Files installed by rocksdb (main library):"
          rpm -ql rocksdb || true
          echo "--- End rpm -ql output ---"
        CIBW_CFLAGS_LINUX: "-I/usr/include/"
        CIBW_LDFLAGS_LINUX: "-L/usr/lib/ -lrocksdb"

        # macOS specific configurations
        CIBW_CFLAGS_MACOS: "-I${{ steps.brew_prefix.outputs.BREW_PREFIX }}/include/"
        CIBW_LDFLAGS_MACOS: "-L${{ steps.brew_prefix.outputs.BREW_PREFIX }}/lib/ -lrocksdb"

        # Windows specific configurations
        # Explicitly target CPython 3.8 on Windows AMD64 (as per previous error)
        CIBW_BUILD_WINDOWS: "cp38-win_amd64"
        CIBW_ARCHS_WINDOWS: "AMD64"
        # Enable pre-release Pythons (allows specific patch versions like 3.8.10)
        CIBW_PRERELEASE_PYTHONS: "True"
        # Force cibuildwheel to re-install Python interpreters using its own robust method
        CIBW_FORCE_INSTALL: "1"
        # Explicitly set the download URL for Python on Windows to avoid NuGet issues
        CIBW_DOWNLOAD_URL_WINDOWS: "https://www.python.org/ftp/python/"
        # Enable debug output for cibuildwheel for more verbose logging
        CIBW_DEBUG: "1"

        # --- CRUCIAL FIX FOR ROCKSDB INCLUDE/LIB PATHS ON WINDOWS ---
        # This script runs before the wheel build and sets environment variables
        # that the MSVC compiler (cl.exe) and linker (link.exe) will use.
        CIBW_BEFORE_BUILD_WINDOWS: |
          $VCPKG_ROOT_WIN = "${{ github.workspace }}\vcpkg"
          $ROCKSDB_INCLUDE_PATH = Join-Path -Path $VCPKG_ROOT_WIN -ChildPath "installed\x64-windows\include"
          $ROCKSDB_LIB_PATH = Join-Path -Path $VCPKG_ROOT_WIN -ChildPath "installed\x64-windows\lib"

          Write-Host "Setting INCLUDE environment variable to include: $ROCKSDB_INCLUDE_PATH"
          Write-Host "Setting LIB environment variable to include: $ROCKSDB_LIB_PATH"

          # Append to existing INCLUDE and LIB environment variables.
          # This is the most reliable way to pass paths to MSVC.
          # 'Process' scope makes it available to child processes (the build).
          [System.Environment]::SetEnvironmentVariable('INCLUDE', "$ROCKSDB_INCLUDE_PATH;" + $env:INCLUDE, 'Process')
          [System.Environment]::SetEnvironmentVariable('LIB', "$ROCKSDB_LIB_PATH;" + $env:LIB, 'Process')

          # Also set CFLAGS and LDFLAGS for setuptools/distutils which might pick these up
          $env:CFLAGS = "-I`"$ROCKSDB_INCLUDE_PATH`"" # Use quoted path for spaces
          $env:LDFLAGS = "-L`"$ROCKSDB_LIB_PATH`" -lrocksdb" # Use quoted path for spaces

          Write-Host "Current INCLUDE environment variable: $env:INCLUDE"
          Write-Host "Current LIB environment variable: $env:LIB"
          Write-Host "Current CFLAGS environment variable: $env:CFLAGS"
          Write-Host "Current LDFLAGS environment variable: $env:LDFLAGS"

        # Remove direct CIBW_CFLAGS_WINDOWS and CIBW_LDFLAGS_WINDOWS as they are
        # now handled by CIBW_BEFORE_BUILD_WINDOWS for better control.
        # CIBW_CFLAGS_WINDOWS: "-I${{ github.workspace }}\\vcpkg\\installed\\x64-windows\\include"
        # CIBW_LDFLAGS_WINDOWS: "-L${{ github.workspace }}\\vcpkg\\installed\\x64-windows\\lib -lrocksdb"

    - name: Upload wheels as artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-wheels
        path: ./wheelhouse/*.whl
