name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    name: Upload prebuilt wheels to PyPI
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Download wheel artifacts (macOS)
      uses: actions/download-artifact@v4
      with:
        name: python-wheels-macos-latest
        path: dist

    - name: Download wheel artifacts (Linux)
      uses: actions/download-artifact@v4
      with:
        name: python-wheels-ubuntu-latest
        path: dist

    - name: Download wheel artifacts (Windows)
      uses: actions/download-artifact@v4
      with:
        name: python-wheels-windows-latest
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install twine
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Verify contents
      run: |
        echo "Wheels in dist/:"
        ls dist/

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*.whl
