name: Publish to PyPI

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  publish:
    name: Upload to PyPI
    runs-on: ubuntu-latest

    permissions:
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/project/<your-package-name>/  # Optional, for UI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the distribution
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

