# Publish workflow
name: Publish Python Package

on:
  release:
    types: [published] # Trigger this workflow when a new GitHub Release is *published*

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi # This environment name should match what you configure on PyPI for Trusted Publishers
      url: https://pypi.org/p/pyrex-rocksdb # Replace with your PyPI project URL
    permissions:
      id-token: write # IMPORTANT: This permission is mandatory for trusted publishing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Or specific versions like 3.9, 3.10, 3.11

      - name: Install build tools
        run: |
          pip install build twine # Install the necessary tools

      - name: Build sdist and wheel
        run: python -m build # This will use your pyproject.toml configuration

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # Uses Trusted Publishing by default if permissions are set
